# Generated by Django 2.0.7 on 2018-07-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politieker_partij_link',
            old_name='partij_id',
            new_name='partij',
        ),
        migrations.RenameField(
            model_name='politieker_partij_link',
            old_name='politieker_id',
            new_name='politieker',
        ),
    ]
