# Generated by Django 2.0.7 on 2018-07-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0002_auto_20180718_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemeente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('nis', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Gemeente',
                'verbose_name_plural': 'Gemeente',
            },
        ),
    ]
