# Generated by Django 2.0.7 on 2018-07-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0003_gemeente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemeente',
            name='id',
        ),
        migrations.AlterField(
            model_name='gemeente',
            name='nis',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partij',
            name='nis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiestze.Gemeente'),
        ),
    ]
