# Generated by Django 2.0.7 on 2018-07-21 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('kiestze', '0004_auto_20180719_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User_edits',
            fields=[
                ('guid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=100)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('suggested_value', models.CharField(max_length=300)),
                ('politieker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiestze.Politieker')),
            ],
            options={
                'verbose_name': 'User_edits',
                'verbose_name_plural': 'User_edits',
            },
        ),
        migrations.AddField(
            model_name='approver',
            name='aanpassing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiestze.User_edits'),
        ),
        migrations.AddField(
            model_name='approver',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
    ]
