# Generated by Django 2.0.7 on 2018-07-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0005_auto_20180721_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_edits',
            new_name='User_edit',
        ),
        migrations.AlterModelOptions(
            name='user_edit',
            options={'verbose_name': 'User_edit', 'verbose_name_plural': 'User_edit'},
        ),
    ]
