# Generated by Django 2.0.7 on 2018-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0008_auto_20180723_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politieker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
