# Generated by Django 2.0.7 on 2018-07-23 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0009_auto_20180723_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
