# Generated by Django 2.0.7 on 2018-07-24 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0010_auto_20180723_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_edit',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
