# Generated by Django 2.0.7 on 2018-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0011_auto_20180724_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=100)),
            ],
        ),
    ]
