# Generated by Django 2.0.7 on 2018-07-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0012_editablefield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Politieker_partij_link',
            new_name='PolitiekerPartijLink',
        ),
        migrations.RenameModel(
            old_name='User_edit',
            new_name='UserEdit',
        ),
    ]
