# Generated by Django 2.0.7 on 2018-07-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0012_editablefield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Politieker_partij_link',
            new_name='PolitiekerPartijLink',
        ),
        migrations.RenameModel(
            old_name='User_edit',
            new_name='UserEdit',
        ),
        migrations.RenameField(
            model_name='useredit',
            old_name='column_name',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='useredit',
            old_name='guid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='approver',
            name='aanpassing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiestze.User_edit', to_field='id'),
        ),
    ]
