# Generated by Django 2.0.7 on 2018-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0013_auto_20180724_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useredit',
            old_name='column_name',
            new_name='field',
        ),
    ]
