# Generated by Django 2.0.7 on 2018-07-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0014_auto_20180724_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredit',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiestze.EditableField'),
        ),
    ]
