# Generated by Django 2.0.7 on 2018-07-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0015_auto_20180724_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approver',
            options={'verbose_name': 'Approver', 'verbose_name_plural': 'Approver'},
        ),
        migrations.AlterModelOptions(
            name='editablefield',
            options={'verbose_name': 'EditableField', 'verbose_name_plural': 'EditableField'},
        ),
        migrations.AlterModelOptions(
            name='useredit',
            options={'verbose_name': 'UserEdit', 'verbose_name_plural': 'UserEdit'},
        ),
    ]
