# Generated by Django 2.0.7 on 2018-07-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0016_auto_20180724_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editablefield',
            name='fieldname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='editablefield',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
