# Generated by Django 2.0.7 on 2018-07-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0016_auto_20180724_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiekerpartijlink',
            name='verkozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='politiekerpartijlink',
            name='verkozen_volgnummer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='politiekerpartijlink',
            name='volgnummer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='politiekerpartijlink',
            name='voorkeurstemmen',
            field=models.IntegerField(blank=True),
        ),
    ]
