# Generated by Django 2.0.7 on 2018-07-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0017_auto_20180725_0954'),
        ('kiestze', '0017_auto_20180725_1007'),
    ]

    operations = [
    ]
