# Generated by Django 2.0.7 on 2018-07-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0019_auto_20180725_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politieker',
            name='geboorte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
