# Generated by Django 2.0.7 on 2018-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiestze', '0023_auto_20180929_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemeente',
            name='begindatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemeente',
            name='einddatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
